/// Flutter icons TaskListIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TaskListIcons
///      fonts:
///       - asset: fonts/TaskListIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TaskListIcons {
  TaskListIcons._();

  static const _kFontFam = 'TaskListIcons';
  static const String _kFontPkg = null;

  static const IconData search = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
